// Copyright (c) 2026 Elias Bachaalany
// SPDX-License-Identifier: MIT

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let version_path = manifest_dir.join("sdk-protocol-version.json");

    println!("cargo:rerun-if-changed={}", version_path.display());

    let version_file = fs::read_to_string(&version_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", version_path.display()));
    let version = serde_json::from_str::<serde_json::Value>(&version_file)
        .ok()
        .and_then(|value| value.get("version").and_then(|version| version.as_u64()))
        .unwrap_or_else(|| {
            panic!(
                "failed to parse numeric `version` from {}",
                version_path.display()
            )
        });

    let generated = format!(
        "// Code generated by build.rs from sdk-protocol-version.json. DO NOT EDIT.\n\
         \n\
         /// Highest protocol version supported by this SDK.\n\
         /// Sourced from this repository's sdk-protocol-version.json file.\n\
         pub const SDK_PROTOCOL_VERSION: u32 = {version};\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("sdk_protocol_version.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}
